version: '3'

services:
database:
image: mysql
restart: always
environment:
MYSQL_DATABASE: 'crud'
MYSQL_USER: 'root'
MYSQL_PASSWORD: '12345678'
MYSQL_ROOT_PASSWORD: '12345678'
ports:
  - '3306:3306'
expose:
  - '3306'